#:schema https://raw.githubusercontent.com/snilan/wrangler-json-schema/main/wrangler.schema.json

name = "moco"
compatibility_date = "2023-08-18"
main = "src/index.ts"

compatibility_flags = ["nodejs_compat"]
#services = [{ binding = "SELF", service = "moco" }]

[[kv_namespaces]]
binding = "NAMESPACE"
id = "<your KV id here>"

[assets]
directory = "./assets"
bindings = ["ASSETS"]

[vars]
PAD = "7"
DOMAIN = "moco.yukata.dev"
